name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-2022
    steps:
      - name: Print greeting
        run: echo "Hallo Welt!"
      - name: Print goodbye
        run: echo "Done - bye!"
